
export const COUNTRIES = [
    { label: "Afghanistan", value: "AF", callingCode: "93" },
    { label: "Albania", value: "AL", callingCode: "355" },
    { label: "Algeria", value: "DZ", callingCode: "213" },
    { label: "Andorra", value: "AD", callingCode: "376" },
    { label: "Angola", value: "AO", callingCode: "244" },
    { label: "Argentina", value: "AR", callingCode: "54" },
    { label: "Armenia", value: "AM", callingCode: "374" },
    { label: "Australia", value: "AU", callingCode: "61" },
    { label: "Austria", value: "AT", callingCode: "43" },
    { label: "Azerbaijan", value: "AZ", callingCode: "994" },
    { label: "Bahrain", value: "BH", callingCode: "973" },
    { label: "Bangladesh", value: "BD", callingCode: "880" },
    { label: "Belarus", value: "BY", callingCode: "375" },
    { label: "Belgium", value: "BE", callingCode: "32" },
    { label: "Belize", value: "BZ", callingCode: "501" },
    { label: "Benin", value: "BJ", callingCode: "229" },
    { label: "Bhutan", value: "BT", callingCode: "975" },
    { label: "Bolivia", value: "BO", callingCode: "591" },
    { label: "Bosnia and Herzegovina", value: "BA", callingCode: "387" },
    { label: "Botswana", value: "BW", callingCode: "267" },
    { label: "Brazil", value: "BR", callingCode: "55" },
    { label: "Brunei", value: "BN", callingCode: "673" },
    { label: "Bulgaria", value: "BG", callingCode: "359" },
    { label: "Burkina Faso", value: "BF", callingCode: "226" },
    { label: "Cambodia", value: "KH", callingCode: "855" },
    { label: "Cameroon", value: "CM", callingCode: "237" },
    { label: "Canada", value: "CA", callingCode: "1" },
    { label: "Central African Republic", value: "CF", callingCode: "236" },
    { label: "Chad", value: "TD", callingCode: "235" },
    { label: "Chile", value: "CL", callingCode: "56" },
    { label: "China", value: "CN", callingCode: "86" },
    { label: "Colombia", value: "CO", callingCode: "57" },
    { label: "Costa Rica", value: "CR", callingCode: "506" },
    { label: "Croatia", value: "HR", callingCode: "385" },
    { label: "Cyprus", value: "CY", callingCode: "357" },
    { label: "Czech Republic", value: "CZ", callingCode: "420" },
    { label: "Denmark", value: "DK", callingCode: "45" },
    { label: "Dominican Republic", value: "DO", callingCode: "1" },
    { label: "Ecuador", value: "EC", callingCode: "593" },
    { label: "Egypt", value: "EG", callingCode: "20" },
    { label: "El Salvador", value: "SV", callingCode: "503" },
    { label: "Estonia", value: "EE", callingCode: "372" },
    { label: "Ethiopia", value: "ET", callingCode: "251" },
    { label: "Finland", value: "FI", callingCode: "358" },
    { label: "France", value: "FR", callingCode: "33" },
    { label: "Georgia", value: "GE", callingCode: "995" },
    { label: "Germany", value: "DE", callingCode: "49" },
    { label: "Ghana", value: "GH", callingCode: "233" },
    { label: "Greece", value: "GR", callingCode: "30" },
    { label: "Guatemala", value: "GT", callingCode: "502" },
    { label: "Haiti", value: "HT", callingCode: "509" },
    { label: "Honduras", value: "HN", callingCode: "504" },
    { label: "Hong Kong", value: "HK", callingCode: "852" },
    { label: "Hungary", value: "HU", callingCode: "36" },
    { label: "Iceland", value: "IS", callingCode: "354" },
    { label: "India", value: "IN", callingCode: "91" },
    { label: "Indonesia", value: "ID", callingCode: "62" },
    { label: "Ireland", value: "IE", callingCode: "353" },
    { label: "Israel", value: "IL", callingCode: "972" },
    { label: "Italy", value: "IT", callingCode: "39" },
    { label: "Jamaica", value: "JM", callingCode: "1" },
    { label: "Japan", value: "JP", callingCode: "81" },
    { label: "Jordan", value: "JO", callingCode: "962" },
    { label: "Kazakhstan", value: "KZ", callingCode: "7" },
    { label: "Kenya", value: "KE", callingCode: "254" },
    { label: "Kuwait", value: "KW", callingCode: "965" },
    { label: "Latvia", value: "LV", callingCode: "371" },
    { label: "Lebanon", value: "LB", callingCode: "961" },
    { label: "Liechtenstein", value: "LI", callingCode: "423" },
    { label: "Lithuania", value: "LT", callingCode: "370" },
    { label: "Luxembourg", value: "LU", callingCode: "352" },
    { label: "Malaysia", value: "MY", callingCode: "60" },
    { label: "Malta", value: "MT", callingCode: "356" },
    { label: "Mexico", value: "MX", callingCode: "52" },
    { label: "Monaco", value: "MC", callingCode: "377" },
    { label: "Mongolia", value: "MN", callingCode: "976" },
    { label: "Montenegro", value: "ME", callingCode: "382" },
    { label: "Morocco", value: "MA", callingCode: "212" },
    { label: "Nepal", value: "NP", callingCode: "977" },
    { label: "Netherlands", value: "NL", callingCode: "31" },
    { label: "New Zealand", value: "NZ", callingCode: "64" },
    { label: "Nigeria", value: "NG", callingCode: "234" },
    { label: "Norway", value: "NO", callingCode: "47" },
    { label: "Oman", value: "OM", callingCode: "968" },
    { label: "Pakistan", value: "PK", callingCode: "92" },
    { label: "Panama", value: "PA", callingCode: "507" },
    { label: "Paraguay", value: "PY", callingCode: "595" },
    { label: "Peru", value: "PE", callingCode: "51" },
    { label: "Philippines", value: "PH", callingCode: "63" },
    { label: "Poland", value: "PL", callingCode: "48" },
    { label: "Portugal", value: "PT", callingCode: "351" },
    { label: "Qatar", value: "QA", callingCode: "974" },
    { label: "Romania", value: "RO", callingCode: "40" },
    { label: "Russia", value: "RU", callingCode: "7" },
    { label: "Saudi Arabia", value: "SA", callingCode: "966" },
    { label: "Senegal", value: "SN", callingCode: "221" },
    { label: "Serbia", value: "RS", callingCode: "381" },
    { label: "Singapore", value: "SG", callingCode: "65" },
    { label: "Slovakia", value: "SK", callingCode: "421" },
    { label: "Slovenia", value: "SI", callingCode: "386" },
    { label: "South Africa", value: "ZA", callingCode: "27" },
    { label: "South Korea", value: "KR", callingCode: "82" },
    { label: "Spain", value: "ES", callingCode: "34" },
    { label: "Sri Lanka", value: "LK", callingCode: "94" },
    { label: "Sweden", value: "SE", callingCode: "46" },
    { label: "Switzerland", value: "CH", callingCode: "41" },
    { label: "Taiwan", value: "TW", callingCode: "886" },
    { label: "Thailand", value: "TH", callingCode: "66" },
    { label: "Tunisia", value: "TN", callingCode: "216" },
    { label: "Turkey", value: "TR", callingCode: "90" },
    { label: "Ukraine", value: "UA", callingCode: "380" },
    { label: "United Arab Emirates", value: "AE", callingCode: "971" },
    { label: "United Kingdom", value: "GB", callingCode: "44" },
    { label: "United States", value: "US", callingCode: "1" },
    { label: "Uruguay", value: "UY", callingCode: "598" },
    { label: "Uzbekistan", value: "UZ", callingCode: "998" },
    { label: "Venezuela", value: "VE", callingCode: "58" },
    { label: "Vietnam", value: "VN", callingCode: "84" },
];
